package com.freewayemi.merchant.entity;

import com.freewayemi.merchant.commons.dto.Address;
import com.freewayemi.merchant.commons.dto.ConvFeeRate;
import com.freewayemi.merchant.commons.dto.DocumentInfo;
import com.freewayemi.merchant.commons.dto.Mdr;
import com.freewayemi.merchant.commons.entity.*;
import com.freewayemi.merchant.commons.type.PaymentProviderEnum;
import com.freewayemi.merchant.dto.Agreements;
import com.freewayemi.merchant.dto.request.Account;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.List;

@Document(collection = "merchant_users")
@Data
@EqualsAndHashCode(callSuper = true)
public class MerchantUser extends BaseEntity {
    private String type;
    private List<String> domains;
    private String source;
    private String stage;
    private String mobile;
    private String email;
    private String firstName;
    private String lastName;
    private boolean isEmailVerified;
    private boolean isMobileVerified;
    private String status;
    private boolean isDeleted;
    private String displayId;
    private String shopName;
    private String businessName;
    private String category;
    private String subCategory;
    private String mccCode;
    private String pan;
    private String gst;
    private String ownership;
    private Address address;
    private Account account;
    private String qrCode;
    private String smsCode;
    private String storeCode;
    private List<MerchantOffer> offers;
    private String deviceToken;
    private String appType;
    private String appVersion;
    private String referralCode;
    private String referredBy;
    private String returnUrl;
    private String webhookUrl;
    private Params params;
    private PaymentLinkInfo paymentLinkInfo;
    private List<Mdr> mdrs;
    private List<PaymentProviderEnum> supportedProviders;
    private Boolean downPaymentEnabled;
    private List<PaymentProviderInfo> supportedDpProviders;
    private boolean docsSubmit;
    private List<DocumentInfo> documents;
    private Boolean consent;
    private Instant qrActivationDate;
    private Instant approvedDate;
    private Instant consentAcceptDate;
    private Instant appInstalledDate;
    private Instant resubmissionDate;
    private Instant profiledDate;
    private Instant rejectionDate;
    private Instant droppedDate;
    private Boolean dynamicOffers;
    private String dynamicOfferTemplate;
    private String resubmissionReason;
    private String rejectedReason;
    private String droppedReason;
    private Boolean isSeamless;
    private List<String> shareImages;
    private Boolean isGSTVerified;
    private Boolean canCxBuyInsurance;
    private Boolean isConvFee;
    private List<ConvFeeRate> convFeeRates;
    private SecurityCredentials securityCredentials;
    private Boolean isGiftVoucherEnabled;
    private Boolean isInvoiceEnabled;
    private Instant invoiceEnabledDate;
    private MerchantRefundConfig merchantRefundConfig;
    private Boolean isInvoicingModel;
    private Boolean isBrandSubventionModel;
    private String websiteUrl;
    private Boolean isOtpFlow;
    private List<String> onboardingStates;
    private Boolean alteredMobileNumber;
    private Boolean nceOnly;
    private String sigDocNumber;
    private String sigDocType;
    private String softQrCode;
    private Boolean hideOtherProducts;
    private MerchantKycInfo kyc;
    private Boolean isActivated;
    private Boolean isOnboarded;
    private SettlementConfig settlementConfig;
    private List<String> incentiveIds;
    //eventually it would become a list, for now single master, for servify.
    private String masterMerchants;
    private String parentMerchant;
    private String partner;
    private List<String> partners;
    private List<String> partnerMerchants;
    private String meCode;
    private String merchantTraceId;
    private String ownerDob;
    private Boolean ispaymentMerchant;
    private Agreements agreements;
    private Integer riskCategory;
    private List<ProviderGroup> providerGroups;

}
