package com.freewayemi.merchant.commons.type;

import com.freewayemi.merchant.commons.utils.Util;

import java.util.ArrayList;
import java.util.List;

import static com.freewayemi.merchant.commons.type.BankEnum.*;
import static com.freewayemi.merchant.commons.type.CardTypeEnum.*;
import static com.freewayemi.merchant.commons.type.EmiTenureEnum.*;
import static com.freewayemi.merchant.commons.type.InterestEnum.*;


public enum CardInterestEnum {
    // American Express
    AMEX_3(CREDIT, AMEX, THREE, PER_FOURTEEN),
    AMEX_6(CREDIT, AMEX, SIX, PER_FOURTEEN),
    AMEX_9(CREDIT, AMEX, NINE, PER_FOURTEEN),
    AMEX_12(CREDIT, AMEX, TWELVE, PER_FOURTEEN),
    AMEX_18(CREDIT, AMEX, EIGHTEEN, PER_FOURTEEN),
    AMEX_24(CREDIT, AMEX, TWENTYFOUR, PER_FOURTEEN),

    // Bank of Baroda
    BARB_3(CREDIT, BARB, THREE, PER_THIRTEEN),
    BARB_6(CREDIT, BARB, SIX, PER_FOURTEEN),
    BARB_9(CREDIT, BARB, NINE, PER_FOURTEEN),
    BARB_12(CREDIT, BARB, TWELVE, PER_FIFTEEN),
    BARB_18(CREDIT, BARB, EIGHTEEN, PER_FIFTEEN),
    BARB_24(CREDIT, BARB, TWENTYFOUR, PER_SIXTEEN),
    BARB_36(CREDIT, BARB, THIRTYSIX, PER_SIXTEEN),

    // Citibank
    CITI_3(CREDIT, CITI, THREE, PER_THIRTEEN),
    CITI_6(CREDIT, CITI, SIX, PER_THIRTEEN),
    CITI_9(CREDIT, CITI, NINE, PER_FIFTEEN),
    CITI_12(CREDIT, CITI, TWELVE, PER_FIFTEEN),
    CITI_18(CREDIT, CITI, EIGHTEEN, PER_FIFTEEN),
    CITI_24(CREDIT, CITI, TWENTYFOUR, PER_FIFTEEN),

    HDFC_3(CREDIT, HDFC, THREE, PER_SIXTEEN, PER_SIXTEEN),
    HDFC_6(CREDIT, HDFC, SIX, PER_SIXTEEN, PER_SIXTEEN),
    HDFC_9(CREDIT, HDFC, NINE, PER_SIXTEEN, PER_SIXTEEN),
    HDFC_12(CREDIT, HDFC, TWELVE, PER_SIXTEEN, PER_SIXTEEN),
    HDFC_18(CREDIT, HDFC, EIGHTEEN, PER_SIXTEEN, PER_SIXTEEN),
    HDFC_24(CREDIT, HDFC, TWENTYFOUR, PER_SIXTEEN, PER_SIXTEEN),

    HSBC_3(CREDIT, HSBC, THREE, PER_TWELVE_POINT_FIVE),
    HSBC_6(CREDIT, HSBC, SIX, PER_TWELVE_POINT_FIVE),
    HSBC_9(CREDIT, HSBC, NINE, PER_THIRTEEN_POINT_FIVE),
    HSBC_12(CREDIT, HSBC, TWELVE, PER_THIRTEEN_POINT_FIVE),
    HSBC_18(CREDIT, HSBC, EIGHTEEN, PER_THIRTEEN_POINT_FIVE),
    HSBC_24(CREDIT, HSBC, TWENTYFOUR, PER_FIFTEEN),

    ICIC_3(CREDIT, ICIC, THREE, PER_FIFTEEN_POINT_NINE_NINE),
    ICIC_6(CREDIT, ICIC, SIX, PER_FIFTEEN_POINT_NINE_NINE),
    ICIC_9(CREDIT, ICIC, NINE, PER_FIFTEEN_POINT_NINE_NINE),
    ICIC_12(CREDIT, ICIC, TWELVE, PER_FIFTEEN_POINT_NINE_NINE),
    ICIC_18(CREDIT, ICIC, EIGHTEEN, PER_FIFTEEN_POINT_NINE_NINE),
    ICIC_24(CREDIT, ICIC, TWENTYFOUR, PER_FIFTEEN_POINT_NINE_NINE),

    INDB_3(CREDIT, INDB, THREE, PER_FOURTEEN),
    INDB_6(CREDIT, INDB, SIX, PER_FOURTEEN),
    INDB_9(CREDIT, INDB, NINE, PER_FIFTEEN),
    INDB_12(CREDIT, INDB, TWELVE, PER_FIFTEEN),
    INDB_18(CREDIT, INDB, EIGHTEEN, PER_FIFTEEN),
    INDB_24(CREDIT, INDB, TWENTYFOUR, PER_FIFTEEN),
    INDB_36(CREDIT, INDB, THIRTYSIX, PER_FIFTEEN),

    KKBK_3(CREDIT, KKBK, THREE, PER_SIXTEEN),
    KKBK_6(CREDIT, KKBK, SIX, PER_SIXTEEN),
    KKBK_9(CREDIT, KKBK, NINE, PER_SIXTEEN),
    KKBK_12(CREDIT, KKBK, TWELVE, PER_SIXTEEN),
    KKBK_18(CREDIT, KKBK, EIGHTEEN, PER_SIXTEEN),
    // KKBK_20(CREDIT, KKBK, TWENTY, PER_SIXTEEN),
    KKBK_24(CREDIT, KKBK, TWENTYFOUR, PER_SIXTEEN),
    // KKBK_30(CREDIT, KKBK, THIRTY_M, PER_SIXTEEN),
    KKBK_36(CREDIT, KKBK, THIRTYSIX, PER_SIXTEEN),

    RATN_3(CREDIT, RATN, THREE, PER_THIRTEEN),
    RATN_6(CREDIT, RATN, SIX, PER_FOURTEEN),
    RATN_9(CREDIT, RATN, NINE, PER_FIFTEEN),
    RATN_12(CREDIT, RATN, TWELVE, PER_FIFTEEN),
    RATN_18(CREDIT, RATN, EIGHTEEN, PER_FIFTEEN),
    RATN_24(CREDIT, RATN, TWENTYFOUR, PER_FIFTEEN),

    SBIN_3(CREDIT, SBIN, THREE, PER_SIXTEEN_POINT_FIVE),
    SBIN_6(CREDIT, SBIN, SIX, PER_FIFTEEN),
    SBIN_9(CREDIT, SBIN, NINE, PER_FIFTEEN),
    SBIN_12(CREDIT, SBIN, TWELVE, PER_FIFTEEN),

    SCBL_3(CREDIT, SCBL, THREE, PER_ELEVEN_POINT_EIGHT_EIGHT),
    SCBL_6(CREDIT, SCBL, SIX, PER_THIRTEEN),
    SCBL_9(CREDIT, SCBL, NINE, PER_FOURTEEN),
    SCBL_12(CREDIT, SCBL, TWELVE, PER_FOURTEEN),

    UTIB_3(CREDIT, UTIB, THREE, PER_FOURTEEN),
    UTIB_6(CREDIT, UTIB, SIX, PER_FOURTEEN),
    UTIB_9(CREDIT, UTIB, NINE, PER_FIFTEEN),
    UTIB_12(CREDIT, UTIB, TWELVE, PER_FIFTEEN),
    UTIB_18(CREDIT, UTIB, EIGHTEEN, PER_SIXTEEN),
    UTIB_24(CREDIT, UTIB, TWENTYFOUR, PER_SIXTEEN),

    YESB_3(CREDIT, YESB, THREE, PER_FOURTEEN),
    YESB_6(CREDIT, YESB, SIX, PER_FOURTEEN),
    YESB_9(CREDIT, YESB, NINE, PER_FOURTEEN),
    YESB_12(CREDIT, YESB, TWELVE, PER_FIFTEEN),
    YESB_18(CREDIT, YESB, EIGHTEEN, PER_FIFTEEN),
    YESB_24(CREDIT, YESB, TWENTYFOUR, PER_FIFTEEN),

    D_HDFC_3(DEBIT, HDFC, THREE, PER_SIXTEEN),
    D_HDFC_6(DEBIT, HDFC, SIX, PER_SIXTEEN),
    D_HDFC_9(DEBIT, HDFC, NINE, PER_SIXTEEN),
    D_HDFC_12(DEBIT, HDFC, TWELVE, PER_SIXTEEN),
    D_HDFC_18(DEBIT, HDFC, EIGHTEEN, PER_SIXTEEN),
    D_HDFC_24(DEBIT, HDFC, TWENTYFOUR, PER_SIXTEEN),

    D_IDFC_3(DEBIT, IDFC, THREE, PER_SIXTEEN),
    D_IDFC_6(DEBIT, IDFC, SIX, PER_SIXTEEN),
    D_IDFC_9(DEBIT, IDFC, NINE, PER_SIXTEEN),
    D_IDFC_12(DEBIT, IDFC, TWELVE, PER_SIXTEEN),
    D_IDFC_18(DEBIT, IDFC, EIGHTEEN, PER_SIXTEEN),

    D_UTIB_3(DEBIT, UTIB, THREE, PER_FOURTEEN),
    D_UTIB_6(DEBIT, UTIB, SIX, PER_FOURTEEN),
    D_UTIB_9(DEBIT, UTIB, NINE, PER_SIXTEEN),
    D_UTIB_12(DEBIT, UTIB, TWELVE, PER_SIXTEEN),
    D_UTIB_18(DEBIT, UTIB, EIGHTEEN, PER_SIXTEEN),
    D_UTIB_24(DEBIT, UTIB, TWENTYFOUR, PER_SIXTEEN),

    D_ICIC_3(DEBIT, ICIC, THREE, PER_SIXTEEN),
    D_ICIC_6(DEBIT, ICIC, SIX, PER_SIXTEEN),
    D_ICIC_9(DEBIT, ICIC, NINE, PER_SIXTEEN),
    D_ICIC_12(DEBIT, ICIC, TWELVE, PER_SIXTEEN),
//	D_ICIC_18(DEBIT, ICIC, EIGHTEEN, PER_SIXTEEN),
//	D_ICIC_24(DEBIT, ICIC, TWENTYFOUR, PER_SIXTEEN);
//	D_ICIC_36(DEBIT, ICIC, THIRTYSIX, PER_SIXTEEN);

    D_KKBK_3(DEBIT, KKBK, THREE, PER_TWENTY_TWO, THREE, PER_NINETEEN),
    D_KKBK_6(DEBIT, KKBK, SIX, PER_TWENTY_TWO, SIX, PER_NINETEEN),
    D_KKBK_9(DEBIT, KKBK, NINE, PER_TWENTY_TWO, NINE, PER_NINETEEN),
    D_KKBK_12(DEBIT, KKBK, TWELVE, PER_TWENTY_TWO, TWELVE, PER_NINETEEN),

    D_CL_ICICI_3(CARDLESS, CL_ICICI, THREE, PER_SEVENTEEN),
    D_CL_ICICI_6(CARDLESS, CL_ICICI, SIX, PER_SEVENTEEN),
    D_CL_ICICI_9(CARDLESS, CL_ICICI, NINE, PER_SEVENTEEN),
    D_CL_ICICI_12(CARDLESS, CL_ICICI, TWELVE, PER_SEVENTEEN),
    D_CL_ICICI_15(CARDLESS, CL_ICICI, FIFTEEN, PER_SEVENTEEN),
    D_CL_ICICI_18(CARDLESS, CL_ICICI, EIGHTEEN, PER_SEVENTEEN),
    D_CL_ICICI_24(CARDLESS, CL_ICICI, TWENTYFOUR, PER_SEVENTEEN),

    D_CL_ICICI_KYC_3(CARDLESS, CL_ICICI_KYC, THREE, PER_SIXTEEN),
    D_CL_ICICI_KYC_6(CARDLESS, CL_ICICI_KYC, SIX, PER_SIXTEEN),
    D_CL_ICICI_KYC_9(CARDLESS, CL_ICICI_KYC, NINE, PER_SIXTEEN),
    D_CL_ICICI_KYC_12(CARDLESS, CL_ICICI_KYC, TWELVE, PER_SIXTEEN),
    D_CL_ICICI_KYC_15(CARDLESS, CL_ICICI_KYC, FIFTEEN, PER_SIXTEEN),
    D_CL_ICICI_KYC_18(CARDLESS, CL_ICICI_KYC, EIGHTEEN, PER_SIXTEEN),
    D_CL_ICICI_KYC_24(CARDLESS, CL_ICICI_KYC, TWENTYFOUR, PER_SIXTEEN),


    BNPL_HDFC_15(BNPL, BNPL_HDFC, FIFTEEN_DAY, PER_FOURTEEN),
//    BNPL_HDFC_30(BNPL, BNPL_HDFC, THIRTY, PER_TWENTY_EIGHT),
//    BNPL_HDFC_60(BNPL, BNPL_HDFC, SIXTY, PER_TWENTY_EIGHT),
//    BNPL_HDFC_90(BNPL, BNPL_HDFC, NINETY, PER_TWENTY_EIGHT),

    NTB_IIFL_3(NTB, IIFL, THREE, PER_TWENTY_TWO, THREE),
    NTB_IIFL_6(NTB, IIFL, SIX, PER_TWENTY_TWO, FOUR),
    NTB_IIFL_9(NTB, IIFL, NINE, PER_TWENTY_TWO, SIX),
    NTB_IIFL_12(NTB, IIFL, TWELVE, PER_TWENTY_TWO, EIGHT),
    NTB_IIFL_18(NTB, IIFL, EIGHTEEN, PER_TWENTY_TWO, TWELVE),

    AUFB_3(CREDIT, AUFB, THREE, PER_FOURTEEN),
    AUFB_6(CREDIT, AUFB, SIX, PER_FOURTEEN),
    AUFB_9(CREDIT, AUFB, NINE, PER_FOURTEEN),
    AUFB_12(CREDIT, AUFB, TWELVE, PER_FOURTEEN),
    AUFB_18(CREDIT, AUFB, EIGHTEEN, PER_FOURTEEN),
    AUFB_24(CREDIT, AUFB, TWENTYFOUR, PER_FOURTEEN),

    NTB_HDFC_3(NTB, HDFC_NTB, THREE, PER_TWENTY_TWO),
    NTB_HDFC_6(NTB, HDFC_NTB, SIX, PER_TWENTY_TWO),
    NTB_HDFC_9(NTB, HDFC_NTB, NINE, PER_TWENTY_TWO),
    NTB_HDFC_12(NTB, HDFC_NTB, TWELVE, PER_TWENTY_TWO),

    NTB_KKBK_3(NTB, KKBK, THREE, PER_TWENTY_TWO, THREE),
    NTB_KKBK_6(NTB, KKBK, SIX, PER_TWENTY_TWO, SIX),
    NTB_KKBK_9(NTB, KKBK, NINE, PER_TWENTY_TWO, NINE),
    NTB_KKBK_12(NTB, KKBK, TWELVE, PER_TWENTY_TWO, TWELVE),

    ONECARD_3(CREDIT, ONECARD, THREE, PER_SIXTEEN),
    ONECARD_6(CREDIT, ONECARD, SIX, PER_SIXTEEN),
    ONECARD_9(CREDIT, ONECARD, NINE, PER_SIXTEEN),
    ONECARD_12(CREDIT, ONECARD, TWELVE, PER_SIXTEEN),
    ONECARD_18(CREDIT, ONECARD, EIGHTEEN, PER_SIXTEEN),
    ONECARD_24(CREDIT, ONECARD, TWENTYFOUR, PER_SIXTEEN),

    NTB_ICICI_3(NTB, ICICI_NTB, THREE, PER_NINETEEN),
    NTB_ICICI_6(NTB, ICICI_NTB, SIX, PER_NINETEEN),
    NTB_ICICI_9(NTB, ICICI_NTB, NINE, PER_NINETEEN),
    NTB_ICICI_12(NTB, ICICI_NTB, TWELVE, PER_NINETEEN);

    private final CardTypeEnum cardTypeEnum;
    private final BankEnum bankEnum;
    private final EmiTenureEnum emiTenureEnum;
    private final InterestEnum interestEnum;
    private final InterestEnum brandInterestEnum;
    private final EmiTenureEnum effectiveEmiTenureEnum;
    private final InterestEnum actualIrr;

    CardInterestEnum(CardTypeEnum cardTypeEnum, BankEnum bankEnum, EmiTenureEnum emiTenureEnum,
                     InterestEnum interestEnum) {
        this.cardTypeEnum = cardTypeEnum;
        this.bankEnum = bankEnum;
        this.emiTenureEnum = emiTenureEnum;
        this.interestEnum = interestEnum;
        this.brandInterestEnum = interestEnum;
        this.effectiveEmiTenureEnum = emiTenureEnum;
        this.actualIrr = interestEnum;
    }

    CardInterestEnum(CardTypeEnum cardTypeEnum, BankEnum bankEnum, EmiTenureEnum emiTenureEnum,
                     InterestEnum interestEnum, EmiTenureEnum effectiveCardInterestEnum) {
        this.cardTypeEnum = cardTypeEnum;
        this.bankEnum = bankEnum;
        this.emiTenureEnum = emiTenureEnum;
        this.interestEnum = interestEnum;
        this.brandInterestEnum = interestEnum;
        this.effectiveEmiTenureEnum = effectiveCardInterestEnum;
        this.actualIrr = interestEnum;
    }

    CardInterestEnum(CardTypeEnum cardTypeEnum, BankEnum bankEnum, EmiTenureEnum emiTenureEnum,
                     InterestEnum interestEnum, InterestEnum brandInterestEnum) {
        this.cardTypeEnum = cardTypeEnum;
        this.bankEnum = bankEnum;
        this.emiTenureEnum = emiTenureEnum;
        this.interestEnum = interestEnum;
        this.brandInterestEnum = brandInterestEnum;
        this.effectiveEmiTenureEnum = emiTenureEnum;
        this.actualIrr = interestEnum;
    }

    CardInterestEnum(CardTypeEnum cardTypeEnum, BankEnum bankEnum, EmiTenureEnum emiTenureEnum,
                     InterestEnum interestEnum, EmiTenureEnum emiTenureEnum1, InterestEnum actualIrr) {
        this.cardTypeEnum = cardTypeEnum;
        this.bankEnum = bankEnum;
        this.emiTenureEnum = emiTenureEnum;
        this.interestEnum = interestEnum;
        this.brandInterestEnum = interestEnum;
        this.effectiveEmiTenureEnum = emiTenureEnum1;
        this.actualIrr = actualIrr;
    }

    public BankEnum getBankEnum() {
        return bankEnum;
    }

    public EmiTenureEnum getEmiTenureEnum() {
        return emiTenureEnum;
    }

    public InterestEnum getInterestEnum() {
        return interestEnum;
    }

    public CardTypeEnum getCardTypeEnum() {
        return cardTypeEnum;
    }
}

/* CC CARDS FROM RAZORPAY
HDFC	3,6,9,12,18,24	PAYU, HDFC, RAZORPAY
CITI	3,6,9,12,18,24	PAYU
ICICI	3,6,9,12,18,24	PAYU, ICICI, CCAVENUE, RAZORPAY
SBI	    3,6,9,12	    PAYU, CCAVENUE
AXIS	3,6,9,12	    PAYU, ICICI, CCAVENUE, RAZORPAY
SCB	    3,6,9,12,18,24	ICICI, PAYU
KOTAK	3,6,9,12	    ICICI, CCAVENUE, PAYU, RAZORPAY
HSBC	3,6,9,12	    ICICI, CCAVENUE, PAYU
AMEX	3,6,9,12	    PAYU, CCAVENUE, RAZORPAY
INDUSIND3,6,9,12,18,24	PAYU, CCAVENUE, RAZORPAY
RBL	    3,6,9,12,18,24	RAZORPAY, PAYU
YES	    3,6,9,12,18,24	PAYU
ICICIDC	3,6,9,12	    PAYU
AXISDC	3,6,9,12	    PAYU
 */

